// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v7.36.2
// source: enum.proto

/* eslint-disable */

export const protobufPackage = "player";

export enum Gender {
  FEMALE = 0,
  MALE = 1,
  UNRECOGNIZED = -1,
}

export function genderFromJSON(object: any): Gender {
  switch (object) {
    case 0:
    case "FEMALE":
      return Gender.FEMALE;
    case 1:
    case "MALE":
      return Gender.MALE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Gender.UNRECOGNIZED;
  }
}

export function genderToJSON(object: Gender): string {
  switch (object) {
    case Gender.FEMALE:
      return "FEMALE";
    case Gender.MALE:
      return "MALE";
    case Gender.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum PlayerType {
  UNSPECIFIED = 0,
  NORMAL = 1,
  GLIFE = 2,
  HOTELAPP = 3,
  GCASH = 4,
  MAYA = 5,
  TONGITSAPP = 6,
  VIBER = 7,
  LAZADA = 8,
  FACEBOOK = 9,
  TELEGRAM = 10,
  CASINO = 11,
  FACEID = 12,
  GOOGLE = 13,
  APPLE = 14,
  PASSKEY = 15,
  UNRECOGNIZED = -1,
}

export function playerTypeFromJSON(object: any): PlayerType {
  switch (object) {
    case 0:
    case "PLAYER_TYPE_UNSPECIFIED":
      return PlayerType.UNSPECIFIED;
    case 1:
    case "PLAYER_TYPE_NORMAL":
      return PlayerType.NORMAL;
    case 2:
    case "PLAYER_TYPE_GLIFE":
      return PlayerType.GLIFE;
    case 3:
    case "PLAYER_TYPE_HOTELAPP":
      return PlayerType.HOTELAPP;
    case 4:
    case "PLAYER_TYPE_GCASH":
      return PlayerType.GCASH;
    case 5:
    case "PLAYER_TYPE_MAYA":
      return PlayerType.MAYA;
    case 6:
    case "PLAYER_TYPE_TONGITSAPP":
      return PlayerType.TONGITSAPP;
    case 7:
    case "PLAYER_TYPE_VIBER":
      return PlayerType.VIBER;
    case 8:
    case "PLAYER_TYPE_LAZADA":
      return PlayerType.LAZADA;
    case 9:
    case "PLAYER_TYPE_FACEBOOK":
      return PlayerType.FACEBOOK;
    case 10:
    case "PLAYER_TYPE_TELEGRAM":
      return PlayerType.TELEGRAM;
    case 11:
    case "PLAYER_TYPE_CASINO":
      return PlayerType.CASINO;
    case 12:
    case "PLAYER_TYPE_FACEID":
      return PlayerType.FACEID;
    case 13:
    case "PLAYER_TYPE_GOOGLE":
      return PlayerType.GOOGLE;
    case 14:
    case "PLAYER_TYPE_APPLE":
      return PlayerType.APPLE;
    case 15:
    case "PLAYER_TYPE_PASSKEY":
      return PlayerType.PASSKEY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PlayerType.UNRECOGNIZED;
  }
}

export function playerTypeToJSON(object: PlayerType): string {
  switch (object) {
    case PlayerType.UNSPECIFIED:
      return "PLAYER_TYPE_UNSPECIFIED";
    case PlayerType.NORMAL:
      return "PLAYER_TYPE_NORMAL";
    case PlayerType.GLIFE:
      return "PLAYER_TYPE_GLIFE";
    case PlayerType.HOTELAPP:
      return "PLAYER_TYPE_HOTELAPP";
    case PlayerType.GCASH:
      return "PLAYER_TYPE_GCASH";
    case PlayerType.MAYA:
      return "PLAYER_TYPE_MAYA";
    case PlayerType.TONGITSAPP:
      return "PLAYER_TYPE_TONGITSAPP";
    case PlayerType.VIBER:
      return "PLAYER_TYPE_VIBER";
    case PlayerType.LAZADA:
      return "PLAYER_TYPE_LAZADA";
    case PlayerType.FACEBOOK:
      return "PLAYER_TYPE_FACEBOOK";
    case PlayerType.TELEGRAM:
      return "PLAYER_TYPE_TELEGRAM";
    case PlayerType.CASINO:
      return "PLAYER_TYPE_CASINO";
    case PlayerType.FACEID:
      return "PLAYER_TYPE_FACEID";
    case PlayerType.GOOGLE:
      return "PLAYER_TYPE_GOOGLE";
    case PlayerType.APPLE:
      return "PLAYER_TYPE_APPLE";
    case PlayerType.PASSKEY:
      return "PLAYER_TYPE_PASSKEY";
    case PlayerType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SubjectType {
  UNSPECIFIED = 0,
  PARTNER = 1,
  PLAYER = 2,
  UNRECOGNIZED = -1,
}

export function subjectTypeFromJSON(object: any): SubjectType {
  switch (object) {
    case 0:
    case "SUBJECT_TYPE_UNSPECIFIED":
      return SubjectType.UNSPECIFIED;
    case 1:
    case "SUBJECT_TYPE_PARTNER":
      return SubjectType.PARTNER;
    case 2:
    case "SUBJECT_TYPE_PLAYER":
      return SubjectType.PLAYER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SubjectType.UNRECOGNIZED;
  }
}

export function subjectTypeToJSON(object: SubjectType): string {
  switch (object) {
    case SubjectType.UNSPECIFIED:
      return "SUBJECT_TYPE_UNSPECIFIED";
    case SubjectType.PARTNER:
      return "SUBJECT_TYPE_PARTNER";
    case SubjectType.PLAYER:
      return "SUBJECT_TYPE_PLAYER";
    case SubjectType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Rejection CATEGORY — for FPMS table display + DB. Logic keys on AiKycRejectRemark, not this. */
export enum AiKycRejectReason {
  UNSPECIFIED = 0,
  INVALID_ID = 1,
  VERIFY_PHOTO_REJECT = 2,
  TAMPERED_ID = 3,
  /** ACCOUNT_ISSUE - 账号问题 */
  ACCOUNT_ISSUE = 4,
  /** HIGH_RISK - 高危 */
  HIGH_RISK = 5,
  UNRECOGNIZED = -1,
}

export function aiKycRejectReasonFromJSON(object: any): AiKycRejectReason {
  switch (object) {
    case 0:
    case "AI_KYC_REJECT_REASON_UNSPECIFIED":
      return AiKycRejectReason.UNSPECIFIED;
    case 1:
    case "AI_KYC_REJECT_REASON_INVALID_ID":
      return AiKycRejectReason.INVALID_ID;
    case 2:
    case "AI_KYC_REJECT_REASON_VERIFY_PHOTO_REJECT":
      return AiKycRejectReason.VERIFY_PHOTO_REJECT;
    case 3:
    case "AI_KYC_REJECT_REASON_TAMPERED_ID":
      return AiKycRejectReason.TAMPERED_ID;
    case 4:
    case "AI_KYC_REJECT_REASON_ACCOUNT_ISSUE":
      return AiKycRejectReason.ACCOUNT_ISSUE;
    case 5:
    case "AI_KYC_REJECT_REASON_HIGH_RISK":
      return AiKycRejectReason.HIGH_RISK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AiKycRejectReason.UNRECOGNIZED;
  }
}

export function aiKycRejectReasonToJSON(object: AiKycRejectReason): string {
  switch (object) {
    case AiKycRejectReason.UNSPECIFIED:
      return "AI_KYC_REJECT_REASON_UNSPECIFIED";
    case AiKycRejectReason.INVALID_ID:
      return "AI_KYC_REJECT_REASON_INVALID_ID";
    case AiKycRejectReason.VERIFY_PHOTO_REJECT:
      return "AI_KYC_REJECT_REASON_VERIFY_PHOTO_REJECT";
    case AiKycRejectReason.TAMPERED_ID:
      return "AI_KYC_REJECT_REASON_TAMPERED_ID";
    case AiKycRejectReason.ACCOUNT_ISSUE:
      return "AI_KYC_REJECT_REASON_ACCOUNT_ISSUE";
    case AiKycRejectReason.HIGH_RISK:
      return "AI_KYC_REJECT_REASON_HIGH_RISK";
    case AiKycRejectReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * 24 specific remarks — drives permission + credibility logic. This is the "code".
 * Values are append-only (renumbering breaks stored codes), so the comment groups
 * below reflect AiKycRejectReason and NOT the newer 8-group DISPLAY categories —
 * those live in the server catalogs (NT ai-kyc-remark-catalog.ts / FPMS
 * constKycIdRejectReason.js), derived per code.
 */
export enum AiKycRejectRemark {
  UNSPECIFIED = 0,
  /** ACCOUNT_NAME_MISMATCH - Invalid ID (无效ID) */
  ACCOUNT_NAME_MISMATCH = 1,
  /** DOB_MISMATCH - 生日不匹配 */
  DOB_MISMATCH = 2,
  /** UNSUPPORTED_ID_TYPE - 不支持证件类型 */
  UNSUPPORTED_ID_TYPE = 3,
  /** ID_HOLDING_MISMATCH - 上传ID和手持ID不一致 */
  ID_HOLDING_MISMATCH = 4,
  /** BLURRED - 模糊 */
  BLURRED = 5,
  /** EXPIRED - 过期 */
  EXPIRED = 6,
  /** NO_DOB - 缺少生日日期 */
  NO_DOB = 7,
  /** SCANNED - 扫描件 */
  SCANNED = 8,
  /** SELFIE_WITHOUT_VALID_ID - 自拍时未持有效身份证件 */
  SELFIE_WITHOUT_VALID_ID = 9,
  /** UNRECOGNIZABLE_PHOTO - 图片无法识别 */
  UNRECOGNIZABLE_PHOTO = 10,
  /** OTHER - 其它 */
  OTHER = 11,
  /** MULTIPLE_ACCOUNTS - Account issue (账号问题) */
  MULTIPLE_ACCOUNTS = 12,
  /** DUPLICATE_FACE - 重复人脸 */
  DUPLICATE_FACE = 13,
  /** NO_FACE_OR_SELFIE_ID - VerifyPhoto Reject (脸部验证失败) */
  NO_FACE_OR_SELFIE_ID = 14,
  /** FACE_NOT_SAME_AS_ID - 脸与ID照片不一致 */
  FACE_NOT_SAME_AS_ID = 15,
  /** FACE_BLUR_OR_COVERED - 脸部模糊或遮挡 */
  FACE_BLUR_OR_COVERED = 16,
  /** EDITED_PHOTO - Tampered ID (篡改ID) */
  EDITED_PHOTO = 17,
  /** EDITED_TEXT - 修改内容 */
  EDITED_TEXT = 18,
  /** AI_GENERATED - AI生成图片 */
  AI_GENERATED = 19,
  /** GOV_NDRP - High-risk (高危) */
  GOV_NDRP = 20,
  /** UNDERAGE - 低于21岁 */
  UNDERAGE = 21,
  /** ABNORMAL_PLAYER - 异常KYC玩家 */
  ABNORMAL_PLAYER = 22,
  /** SCREEN_CAPTURED_PHOTO - Invalid ID tier (behaves as INVALID_ID); display category 证件图片质量问题 ID Photo Quality Issue */
  SCREEN_CAPTURED_PHOTO = 23,
  /** NOT_ID_PHOTO - 不是证件照 */
  NOT_ID_PHOTO = 24,
  UNRECOGNIZED = -1,
}

export function aiKycRejectRemarkFromJSON(object: any): AiKycRejectRemark {
  switch (object) {
    case 0:
    case "AI_KYC_REJECT_REMARK_UNSPECIFIED":
      return AiKycRejectRemark.UNSPECIFIED;
    case 1:
    case "AI_KYC_REJECT_REMARK_ACCOUNT_NAME_MISMATCH":
      return AiKycRejectRemark.ACCOUNT_NAME_MISMATCH;
    case 2:
    case "AI_KYC_REJECT_REMARK_DOB_MISMATCH":
      return AiKycRejectRemark.DOB_MISMATCH;
    case 3:
    case "AI_KYC_REJECT_REMARK_UNSUPPORTED_ID_TYPE":
      return AiKycRejectRemark.UNSUPPORTED_ID_TYPE;
    case 4:
    case "AI_KYC_REJECT_REMARK_ID_HOLDING_MISMATCH":
      return AiKycRejectRemark.ID_HOLDING_MISMATCH;
    case 5:
    case "AI_KYC_REJECT_REMARK_BLURRED":
      return AiKycRejectRemark.BLURRED;
    case 6:
    case "AI_KYC_REJECT_REMARK_EXPIRED":
      return AiKycRejectRemark.EXPIRED;
    case 7:
    case "AI_KYC_REJECT_REMARK_NO_DOB":
      return AiKycRejectRemark.NO_DOB;
    case 8:
    case "AI_KYC_REJECT_REMARK_SCANNED":
      return AiKycRejectRemark.SCANNED;
    case 9:
    case "AI_KYC_REJECT_REMARK_SELFIE_WITHOUT_VALID_ID":
      return AiKycRejectRemark.SELFIE_WITHOUT_VALID_ID;
    case 10:
    case "AI_KYC_REJECT_REMARK_UNRECOGNIZABLE_PHOTO":
      return AiKycRejectRemark.UNRECOGNIZABLE_PHOTO;
    case 11:
    case "AI_KYC_REJECT_REMARK_OTHER":
      return AiKycRejectRemark.OTHER;
    case 12:
    case "AI_KYC_REJECT_REMARK_MULTIPLE_ACCOUNTS":
      return AiKycRejectRemark.MULTIPLE_ACCOUNTS;
    case 13:
    case "AI_KYC_REJECT_REMARK_DUPLICATE_FACE":
      return AiKycRejectRemark.DUPLICATE_FACE;
    case 14:
    case "AI_KYC_REJECT_REMARK_NO_FACE_OR_SELFIE_ID":
      return AiKycRejectRemark.NO_FACE_OR_SELFIE_ID;
    case 15:
    case "AI_KYC_REJECT_REMARK_FACE_NOT_SAME_AS_ID":
      return AiKycRejectRemark.FACE_NOT_SAME_AS_ID;
    case 16:
    case "AI_KYC_REJECT_REMARK_FACE_BLUR_OR_COVERED":
      return AiKycRejectRemark.FACE_BLUR_OR_COVERED;
    case 17:
    case "AI_KYC_REJECT_REMARK_EDITED_PHOTO":
      return AiKycRejectRemark.EDITED_PHOTO;
    case 18:
    case "AI_KYC_REJECT_REMARK_EDITED_TEXT":
      return AiKycRejectRemark.EDITED_TEXT;
    case 19:
    case "AI_KYC_REJECT_REMARK_AI_GENERATED":
      return AiKycRejectRemark.AI_GENERATED;
    case 20:
    case "AI_KYC_REJECT_REMARK_GOV_NDRP":
      return AiKycRejectRemark.GOV_NDRP;
    case 21:
    case "AI_KYC_REJECT_REMARK_UNDERAGE":
      return AiKycRejectRemark.UNDERAGE;
    case 22:
    case "AI_KYC_REJECT_REMARK_ABNORMAL_PLAYER":
      return AiKycRejectRemark.ABNORMAL_PLAYER;
    case 23:
    case "AI_KYC_REJECT_REMARK_SCREEN_CAPTURED_PHOTO":
      return AiKycRejectRemark.SCREEN_CAPTURED_PHOTO;
    case 24:
    case "AI_KYC_REJECT_REMARK_NOT_ID_PHOTO":
      return AiKycRejectRemark.NOT_ID_PHOTO;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AiKycRejectRemark.UNRECOGNIZED;
  }
}

export function aiKycRejectRemarkToJSON(object: AiKycRejectRemark): string {
  switch (object) {
    case AiKycRejectRemark.UNSPECIFIED:
      return "AI_KYC_REJECT_REMARK_UNSPECIFIED";
    case AiKycRejectRemark.ACCOUNT_NAME_MISMATCH:
      return "AI_KYC_REJECT_REMARK_ACCOUNT_NAME_MISMATCH";
    case AiKycRejectRemark.DOB_MISMATCH:
      return "AI_KYC_REJECT_REMARK_DOB_MISMATCH";
    case AiKycRejectRemark.UNSUPPORTED_ID_TYPE:
      return "AI_KYC_REJECT_REMARK_UNSUPPORTED_ID_TYPE";
    case AiKycRejectRemark.ID_HOLDING_MISMATCH:
      return "AI_KYC_REJECT_REMARK_ID_HOLDING_MISMATCH";
    case AiKycRejectRemark.BLURRED:
      return "AI_KYC_REJECT_REMARK_BLURRED";
    case AiKycRejectRemark.EXPIRED:
      return "AI_KYC_REJECT_REMARK_EXPIRED";
    case AiKycRejectRemark.NO_DOB:
      return "AI_KYC_REJECT_REMARK_NO_DOB";
    case AiKycRejectRemark.SCANNED:
      return "AI_KYC_REJECT_REMARK_SCANNED";
    case AiKycRejectRemark.SELFIE_WITHOUT_VALID_ID:
      return "AI_KYC_REJECT_REMARK_SELFIE_WITHOUT_VALID_ID";
    case AiKycRejectRemark.UNRECOGNIZABLE_PHOTO:
      return "AI_KYC_REJECT_REMARK_UNRECOGNIZABLE_PHOTO";
    case AiKycRejectRemark.OTHER:
      return "AI_KYC_REJECT_REMARK_OTHER";
    case AiKycRejectRemark.MULTIPLE_ACCOUNTS:
      return "AI_KYC_REJECT_REMARK_MULTIPLE_ACCOUNTS";
    case AiKycRejectRemark.DUPLICATE_FACE:
      return "AI_KYC_REJECT_REMARK_DUPLICATE_FACE";
    case AiKycRejectRemark.NO_FACE_OR_SELFIE_ID:
      return "AI_KYC_REJECT_REMARK_NO_FACE_OR_SELFIE_ID";
    case AiKycRejectRemark.FACE_NOT_SAME_AS_ID:
      return "AI_KYC_REJECT_REMARK_FACE_NOT_SAME_AS_ID";
    case AiKycRejectRemark.FACE_BLUR_OR_COVERED:
      return "AI_KYC_REJECT_REMARK_FACE_BLUR_OR_COVERED";
    case AiKycRejectRemark.EDITED_PHOTO:
      return "AI_KYC_REJECT_REMARK_EDITED_PHOTO";
    case AiKycRejectRemark.EDITED_TEXT:
      return "AI_KYC_REJECT_REMARK_EDITED_TEXT";
    case AiKycRejectRemark.AI_GENERATED:
      return "AI_KYC_REJECT_REMARK_AI_GENERATED";
    case AiKycRejectRemark.GOV_NDRP:
      return "AI_KYC_REJECT_REMARK_GOV_NDRP";
    case AiKycRejectRemark.UNDERAGE:
      return "AI_KYC_REJECT_REMARK_UNDERAGE";
    case AiKycRejectRemark.ABNORMAL_PLAYER:
      return "AI_KYC_REJECT_REMARK_ABNORMAL_PLAYER";
    case AiKycRejectRemark.SCREEN_CAPTURED_PHOTO:
      return "AI_KYC_REJECT_REMARK_SCREEN_CAPTURED_PHOTO";
    case AiKycRejectRemark.NOT_ID_PHOTO:
      return "AI_KYC_REJECT_REMARK_NOT_ID_PHOTO";
    case AiKycRejectRemark.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}
