// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v7.36.2
// source: type.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "player";

export enum MergePlayerStatus {
  DEFAULT = 0,
  ONGOING = 1,
  HAS_PENDING_PROPOSAL = 2,
  FAILED = 3,
  SUCCESS = 4,
  UNRECOGNIZED = -1,
}

export function mergePlayerStatusFromJSON(object: any): MergePlayerStatus {
  switch (object) {
    case 0:
    case "MERGE_PLAYER_STATUS_DEFAULT":
      return MergePlayerStatus.DEFAULT;
    case 1:
    case "MERGE_PLAYER_STATUS_ONGOING":
      return MergePlayerStatus.ONGOING;
    case 2:
    case "MERGE_PLAYER_STATUS_HAS_PENDING_PROPOSAL":
      return MergePlayerStatus.HAS_PENDING_PROPOSAL;
    case 3:
    case "MERGE_PLAYER_STATUS_FAILED":
      return MergePlayerStatus.FAILED;
    case 4:
    case "MERGE_PLAYER_STATUS_SUCCESS":
      return MergePlayerStatus.SUCCESS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MergePlayerStatus.UNRECOGNIZED;
  }
}

export function mergePlayerStatusToJSON(object: MergePlayerStatus): string {
  switch (object) {
    case MergePlayerStatus.DEFAULT:
      return "MERGE_PLAYER_STATUS_DEFAULT";
    case MergePlayerStatus.ONGOING:
      return "MERGE_PLAYER_STATUS_ONGOING";
    case MergePlayerStatus.HAS_PENDING_PROPOSAL:
      return "MERGE_PLAYER_STATUS_HAS_PENDING_PROPOSAL";
    case MergePlayerStatus.FAILED:
      return "MERGE_PLAYER_STATUS_FAILED";
    case MergePlayerStatus.SUCCESS:
      return "MERGE_PLAYER_STATUS_SUCCESS";
    case MergePlayerStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum EmailVerificationStatus {
  NOT_VERIFIED = 0,
  VERIFIED = 1,
  UNBINDED = 2,
  UNRECOGNIZED = -1,
}

export function emailVerificationStatusFromJSON(object: any): EmailVerificationStatus {
  switch (object) {
    case 0:
    case "NOT_VERIFIED":
      return EmailVerificationStatus.NOT_VERIFIED;
    case 1:
    case "VERIFIED":
      return EmailVerificationStatus.VERIFIED;
    case 2:
    case "UNBINDED":
      return EmailVerificationStatus.UNBINDED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EmailVerificationStatus.UNRECOGNIZED;
  }
}

export function emailVerificationStatusToJSON(object: EmailVerificationStatus): string {
  switch (object) {
    case EmailVerificationStatus.NOT_VERIFIED:
      return "NOT_VERIFIED";
    case EmailVerificationStatus.VERIFIED:
      return "VERIFIED";
    case EmailVerificationStatus.UNBINDED:
      return "UNBINDED";
    case EmailVerificationStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Decimal {
  value: number;
  precision: number;
}

export interface BigDecimal {
  value: number;
  precision: number;
}

export interface PlayerMail {
  id: string;
  platformId: string;
  recipientType: string;
  recipientId: string;
  title?: string | undefined;
  content?: string | undefined;
  createTime: string;
  hasBeenRead: boolean;
  bDelete: boolean;
  childPlatformId?: number | undefined;
}

export interface LoginMethodConfig {
  phoneNumberLoginWithPassword?: boolean | undefined;
  playerLoginOrRegisterWithSMS?: boolean | undefined;
  playerLoginOrRegisterWithViber?: boolean | undefined;
  playerLoginOrRegisterWithFacebook?: boolean | undefined;
  biometric?: boolean | undefined;
  emailLoginWithPassword?: boolean | undefined;
  playerLoginOrRegisterWithEmailSMS?: boolean | undefined;
  playerLoginOrRegisterWithTelegram?: boolean | undefined;
  playerLoginOrRegisterWithWhatsapp?: boolean | undefined;
  playerLoginOrRegisterWithApple?: boolean | undefined;
  playerLoginOrRegisterWithPasskey?: boolean | undefined;
}

/** main master toggle + optional iOS/Android sub-toggles */
export interface LoginMethodConfigEntry {
  main: boolean;
  android?: boolean | undefined;
  ios?: boolean | undefined;
}

/** Canonical config per device (H5 / APP / WEB) */
export interface LoginMethodConfigV2 {
  phoneNumberLoginWithPassword?: LoginMethodConfigEntry | undefined;
  playerLoginOrRegisterWithSMS?: LoginMethodConfigEntry | undefined;
  playerLoginOrRegisterWithViber?: LoginMethodConfigEntry | undefined;
  playerLoginOrRegisterWithFacebook?: LoginMethodConfigEntry | undefined;
  biometric?: LoginMethodConfigEntry | undefined;
  emailLoginWithPassword?: LoginMethodConfigEntry | undefined;
  playerLoginOrRegisterWithEmailSMS?: LoginMethodConfigEntry | undefined;
  playerLoginOrRegisterWithTelegram?: LoginMethodConfigEntry | undefined;
  playerLoginOrRegisterWithWhatsapp?: LoginMethodConfigEntry | undefined;
  playerLoginOrRegisterWithApple?: LoginMethodConfigEntry | undefined;
  playerLoginOrRegisterWithPasskey?: LoginMethodConfigEntry | undefined;
}

/** Drag-sort positions for OTP methods */
export interface OtpOrder {
  playerLoginOrRegisterWithSMS?: number | undefined;
  playerLoginOrRegisterWithViber?: number | undefined;
  playerLoginOrRegisterWithEmailSMS?: number | undefined;
  playerLoginOrRegisterWithWhatsapp?: number | undefined;
}

/** Drag-sort positions for third-party methods */
export interface ThirdPartyOrder {
  playerLoginOrRegisterWithFacebook?: number | undefined;
  playerLoginOrRegisterWithTelegram?: number | undefined;
  playerLoginOrRegisterWithApple?: number | undefined;
  biometric?: number | undefined;
  playerLoginOrRegisterWithPasskey?: number | undefined;
}

export interface LoginMethodOrder {
  otp?: OtpOrder | undefined;
  thirdParty?: ThirdPartyOrder | undefined;
}

function createBaseDecimal(): Decimal {
  return { value: 0, precision: 0 };
}

export const Decimal: MessageFns<Decimal> = {
  encode(message: Decimal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== 0) {
      writer.uint32(8).int32(message.value);
    }
    if (message.precision !== 0) {
      writer.uint32(16).int32(message.precision);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Decimal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseDecimal();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.value = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.precision = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): Decimal {
    return {
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      precision: isSet(object.precision) ? globalThis.Number(object.precision) : 0,
    };
  },

  toJSON(message: Decimal): unknown {
    const obj: any = {};
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    if (message.precision !== 0) {
      obj.precision = Math.round(message.precision);
    }
    return obj;
  },

  create(base?: DeepPartial<Decimal>): Decimal {
    return Decimal.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Decimal>): Decimal {
    const message = createBaseDecimal();
    message.value = object.value ?? 0;
    message.precision = object.precision ?? 0;
    return message;
  },
};

function createBaseBigDecimal(): BigDecimal {
  return { value: 0, precision: 0 };
}

export const BigDecimal: MessageFns<BigDecimal> = {
  encode(message: BigDecimal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== 0) {
      writer.uint32(8).int64(message.value);
    }
    if (message.precision !== 0) {
      writer.uint32(16).int32(message.precision);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BigDecimal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseBigDecimal();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.value = longToNumber(reader.int64());
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.precision = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): BigDecimal {
    return {
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
      precision: isSet(object.precision) ? globalThis.Number(object.precision) : 0,
    };
  },

  toJSON(message: BigDecimal): unknown {
    const obj: any = {};
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    if (message.precision !== 0) {
      obj.precision = Math.round(message.precision);
    }
    return obj;
  },

  create(base?: DeepPartial<BigDecimal>): BigDecimal {
    return BigDecimal.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BigDecimal>): BigDecimal {
    const message = createBaseBigDecimal();
    message.value = object.value ?? 0;
    message.precision = object.precision ?? 0;
    return message;
  },
};

function createBasePlayerMail(): PlayerMail {
  return {
    id: "",
    platformId: "",
    recipientType: "",
    recipientId: "",
    title: undefined,
    content: undefined,
    createTime: "",
    hasBeenRead: false,
    bDelete: false,
    childPlatformId: undefined,
  };
}

export const PlayerMail: MessageFns<PlayerMail> = {
  encode(message: PlayerMail, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.platformId !== "") {
      writer.uint32(18).string(message.platformId);
    }
    if (message.recipientType !== "") {
      writer.uint32(26).string(message.recipientType);
    }
    if (message.recipientId !== "") {
      writer.uint32(34).string(message.recipientId);
    }
    if (message.title !== undefined) {
      writer.uint32(42).string(message.title);
    }
    if (message.content !== undefined) {
      writer.uint32(50).string(message.content);
    }
    if (message.createTime !== "") {
      writer.uint32(58).string(message.createTime);
    }
    if (message.hasBeenRead !== false) {
      writer.uint32(64).bool(message.hasBeenRead);
    }
    if (message.bDelete !== false) {
      writer.uint32(72).bool(message.bDelete);
    }
    if (message.childPlatformId !== undefined) {
      writer.uint32(80).int32(message.childPlatformId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerMail {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBasePlayerMail();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.id = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.platformId = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.recipientType = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.recipientId = reader.string();
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.title = reader.string();
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.content = reader.string();
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.createTime = reader.string();
            continue;
          }
          case 8: {
            if (tag !== 64) {
              break;
            }

            message.hasBeenRead = reader.bool();
            continue;
          }
          case 9: {
            if (tag !== 72) {
              break;
            }

            message.bDelete = reader.bool();
            continue;
          }
          case 10: {
            if (tag !== 80) {
              break;
            }

            message.childPlatformId = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): PlayerMail {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      platformId: isSet(object.platformId) ? globalThis.String(object.platformId) : "",
      recipientType: isSet(object.recipientType) ? globalThis.String(object.recipientType) : "",
      recipientId: isSet(object.recipientId) ? globalThis.String(object.recipientId) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : undefined,
      content: isSet(object.content) ? globalThis.String(object.content) : undefined,
      createTime: isSet(object.createTime) ? globalThis.String(object.createTime) : "",
      hasBeenRead: isSet(object.hasBeenRead) ? globalThis.Boolean(object.hasBeenRead) : false,
      bDelete: isSet(object.bDelete) ? globalThis.Boolean(object.bDelete) : false,
      childPlatformId: isSet(object.childPlatformId) ? globalThis.Number(object.childPlatformId) : undefined,
    };
  },

  toJSON(message: PlayerMail): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.platformId !== "") {
      obj.platformId = message.platformId;
    }
    if (message.recipientType !== "") {
      obj.recipientType = message.recipientType;
    }
    if (message.recipientId !== "") {
      obj.recipientId = message.recipientId;
    }
    if (message.title !== undefined) {
      obj.title = message.title;
    }
    if (message.content !== undefined) {
      obj.content = message.content;
    }
    if (message.createTime !== "") {
      obj.createTime = message.createTime;
    }
    if (message.hasBeenRead !== false) {
      obj.hasBeenRead = message.hasBeenRead;
    }
    if (message.bDelete !== false) {
      obj.bDelete = message.bDelete;
    }
    if (message.childPlatformId !== undefined) {
      obj.childPlatformId = Math.round(message.childPlatformId);
    }
    return obj;
  },

  create(base?: DeepPartial<PlayerMail>): PlayerMail {
    return PlayerMail.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<PlayerMail>): PlayerMail {
    const message = createBasePlayerMail();
    message.id = object.id ?? "";
    message.platformId = object.platformId ?? "";
    message.recipientType = object.recipientType ?? "";
    message.recipientId = object.recipientId ?? "";
    message.title = object.title ?? undefined;
    message.content = object.content ?? undefined;
    message.createTime = object.createTime ?? "";
    message.hasBeenRead = object.hasBeenRead ?? false;
    message.bDelete = object.bDelete ?? false;
    message.childPlatformId = object.childPlatformId ?? undefined;
    return message;
  },
};

function createBaseLoginMethodConfig(): LoginMethodConfig {
  return {
    phoneNumberLoginWithPassword: undefined,
    playerLoginOrRegisterWithSMS: undefined,
    playerLoginOrRegisterWithViber: undefined,
    playerLoginOrRegisterWithFacebook: undefined,
    biometric: undefined,
    emailLoginWithPassword: undefined,
    playerLoginOrRegisterWithEmailSMS: undefined,
    playerLoginOrRegisterWithTelegram: undefined,
    playerLoginOrRegisterWithWhatsapp: undefined,
    playerLoginOrRegisterWithApple: undefined,
    playerLoginOrRegisterWithPasskey: undefined,
  };
}

export const LoginMethodConfig: MessageFns<LoginMethodConfig> = {
  encode(message: LoginMethodConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.phoneNumberLoginWithPassword !== undefined) {
      writer.uint32(8).bool(message.phoneNumberLoginWithPassword);
    }
    if (message.playerLoginOrRegisterWithSMS !== undefined) {
      writer.uint32(16).bool(message.playerLoginOrRegisterWithSMS);
    }
    if (message.playerLoginOrRegisterWithViber !== undefined) {
      writer.uint32(24).bool(message.playerLoginOrRegisterWithViber);
    }
    if (message.playerLoginOrRegisterWithFacebook !== undefined) {
      writer.uint32(32).bool(message.playerLoginOrRegisterWithFacebook);
    }
    if (message.biometric !== undefined) {
      writer.uint32(40).bool(message.biometric);
    }
    if (message.emailLoginWithPassword !== undefined) {
      writer.uint32(48).bool(message.emailLoginWithPassword);
    }
    if (message.playerLoginOrRegisterWithEmailSMS !== undefined) {
      writer.uint32(56).bool(message.playerLoginOrRegisterWithEmailSMS);
    }
    if (message.playerLoginOrRegisterWithTelegram !== undefined) {
      writer.uint32(64).bool(message.playerLoginOrRegisterWithTelegram);
    }
    if (message.playerLoginOrRegisterWithWhatsapp !== undefined) {
      writer.uint32(72).bool(message.playerLoginOrRegisterWithWhatsapp);
    }
    if (message.playerLoginOrRegisterWithApple !== undefined) {
      writer.uint32(80).bool(message.playerLoginOrRegisterWithApple);
    }
    if (message.playerLoginOrRegisterWithPasskey !== undefined) {
      writer.uint32(88).bool(message.playerLoginOrRegisterWithPasskey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginMethodConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLoginMethodConfig();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.phoneNumberLoginWithPassword = reader.bool();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.playerLoginOrRegisterWithSMS = reader.bool();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.playerLoginOrRegisterWithViber = reader.bool();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.playerLoginOrRegisterWithFacebook = reader.bool();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.biometric = reader.bool();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.emailLoginWithPassword = reader.bool();
            continue;
          }
          case 7: {
            if (tag !== 56) {
              break;
            }

            message.playerLoginOrRegisterWithEmailSMS = reader.bool();
            continue;
          }
          case 8: {
            if (tag !== 64) {
              break;
            }

            message.playerLoginOrRegisterWithTelegram = reader.bool();
            continue;
          }
          case 9: {
            if (tag !== 72) {
              break;
            }

            message.playerLoginOrRegisterWithWhatsapp = reader.bool();
            continue;
          }
          case 10: {
            if (tag !== 80) {
              break;
            }

            message.playerLoginOrRegisterWithApple = reader.bool();
            continue;
          }
          case 11: {
            if (tag !== 88) {
              break;
            }

            message.playerLoginOrRegisterWithPasskey = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): LoginMethodConfig {
    return {
      phoneNumberLoginWithPassword: isSet(object.phoneNumberLoginWithPassword)
        ? globalThis.Boolean(object.phoneNumberLoginWithPassword)
        : undefined,
      playerLoginOrRegisterWithSMS: isSet(object.playerLoginOrRegisterWithSMS)
        ? globalThis.Boolean(object.playerLoginOrRegisterWithSMS)
        : undefined,
      playerLoginOrRegisterWithViber: isSet(object.playerLoginOrRegisterWithViber)
        ? globalThis.Boolean(object.playerLoginOrRegisterWithViber)
        : undefined,
      playerLoginOrRegisterWithFacebook: isSet(object.playerLoginOrRegisterWithFacebook)
        ? globalThis.Boolean(object.playerLoginOrRegisterWithFacebook)
        : undefined,
      biometric: isSet(object.biometric) ? globalThis.Boolean(object.biometric) : undefined,
      emailLoginWithPassword: isSet(object.emailLoginWithPassword)
        ? globalThis.Boolean(object.emailLoginWithPassword)
        : undefined,
      playerLoginOrRegisterWithEmailSMS: isSet(object.playerLoginOrRegisterWithEmailSMS)
        ? globalThis.Boolean(object.playerLoginOrRegisterWithEmailSMS)
        : undefined,
      playerLoginOrRegisterWithTelegram: isSet(object.playerLoginOrRegisterWithTelegram)
        ? globalThis.Boolean(object.playerLoginOrRegisterWithTelegram)
        : undefined,
      playerLoginOrRegisterWithWhatsapp: isSet(object.playerLoginOrRegisterWithWhatsapp)
        ? globalThis.Boolean(object.playerLoginOrRegisterWithWhatsapp)
        : undefined,
      playerLoginOrRegisterWithApple: isSet(object.playerLoginOrRegisterWithApple)
        ? globalThis.Boolean(object.playerLoginOrRegisterWithApple)
        : undefined,
      playerLoginOrRegisterWithPasskey: isSet(object.playerLoginOrRegisterWithPasskey)
        ? globalThis.Boolean(object.playerLoginOrRegisterWithPasskey)
        : undefined,
    };
  },

  toJSON(message: LoginMethodConfig): unknown {
    const obj: any = {};
    if (message.phoneNumberLoginWithPassword !== undefined) {
      obj.phoneNumberLoginWithPassword = message.phoneNumberLoginWithPassword;
    }
    if (message.playerLoginOrRegisterWithSMS !== undefined) {
      obj.playerLoginOrRegisterWithSMS = message.playerLoginOrRegisterWithSMS;
    }
    if (message.playerLoginOrRegisterWithViber !== undefined) {
      obj.playerLoginOrRegisterWithViber = message.playerLoginOrRegisterWithViber;
    }
    if (message.playerLoginOrRegisterWithFacebook !== undefined) {
      obj.playerLoginOrRegisterWithFacebook = message.playerLoginOrRegisterWithFacebook;
    }
    if (message.biometric !== undefined) {
      obj.biometric = message.biometric;
    }
    if (message.emailLoginWithPassword !== undefined) {
      obj.emailLoginWithPassword = message.emailLoginWithPassword;
    }
    if (message.playerLoginOrRegisterWithEmailSMS !== undefined) {
      obj.playerLoginOrRegisterWithEmailSMS = message.playerLoginOrRegisterWithEmailSMS;
    }
    if (message.playerLoginOrRegisterWithTelegram !== undefined) {
      obj.playerLoginOrRegisterWithTelegram = message.playerLoginOrRegisterWithTelegram;
    }
    if (message.playerLoginOrRegisterWithWhatsapp !== undefined) {
      obj.playerLoginOrRegisterWithWhatsapp = message.playerLoginOrRegisterWithWhatsapp;
    }
    if (message.playerLoginOrRegisterWithApple !== undefined) {
      obj.playerLoginOrRegisterWithApple = message.playerLoginOrRegisterWithApple;
    }
    if (message.playerLoginOrRegisterWithPasskey !== undefined) {
      obj.playerLoginOrRegisterWithPasskey = message.playerLoginOrRegisterWithPasskey;
    }
    return obj;
  },

  create(base?: DeepPartial<LoginMethodConfig>): LoginMethodConfig {
    return LoginMethodConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LoginMethodConfig>): LoginMethodConfig {
    const message = createBaseLoginMethodConfig();
    message.phoneNumberLoginWithPassword = object.phoneNumberLoginWithPassword ?? undefined;
    message.playerLoginOrRegisterWithSMS = object.playerLoginOrRegisterWithSMS ?? undefined;
    message.playerLoginOrRegisterWithViber = object.playerLoginOrRegisterWithViber ?? undefined;
    message.playerLoginOrRegisterWithFacebook = object.playerLoginOrRegisterWithFacebook ?? undefined;
    message.biometric = object.biometric ?? undefined;
    message.emailLoginWithPassword = object.emailLoginWithPassword ?? undefined;
    message.playerLoginOrRegisterWithEmailSMS = object.playerLoginOrRegisterWithEmailSMS ?? undefined;
    message.playerLoginOrRegisterWithTelegram = object.playerLoginOrRegisterWithTelegram ?? undefined;
    message.playerLoginOrRegisterWithWhatsapp = object.playerLoginOrRegisterWithWhatsapp ?? undefined;
    message.playerLoginOrRegisterWithApple = object.playerLoginOrRegisterWithApple ?? undefined;
    message.playerLoginOrRegisterWithPasskey = object.playerLoginOrRegisterWithPasskey ?? undefined;
    return message;
  },
};

function createBaseLoginMethodConfigEntry(): LoginMethodConfigEntry {
  return { main: false, android: undefined, ios: undefined };
}

export const LoginMethodConfigEntry: MessageFns<LoginMethodConfigEntry> = {
  encode(message: LoginMethodConfigEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.main !== false) {
      writer.uint32(8).bool(message.main);
    }
    if (message.android !== undefined) {
      writer.uint32(16).bool(message.android);
    }
    if (message.ios !== undefined) {
      writer.uint32(24).bool(message.ios);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginMethodConfigEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLoginMethodConfigEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.main = reader.bool();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.android = reader.bool();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.ios = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): LoginMethodConfigEntry {
    return {
      main: isSet(object.main) ? globalThis.Boolean(object.main) : false,
      android: isSet(object.android) ? globalThis.Boolean(object.android) : undefined,
      ios: isSet(object.ios) ? globalThis.Boolean(object.ios) : undefined,
    };
  },

  toJSON(message: LoginMethodConfigEntry): unknown {
    const obj: any = {};
    if (message.main !== false) {
      obj.main = message.main;
    }
    if (message.android !== undefined) {
      obj.android = message.android;
    }
    if (message.ios !== undefined) {
      obj.ios = message.ios;
    }
    return obj;
  },

  create(base?: DeepPartial<LoginMethodConfigEntry>): LoginMethodConfigEntry {
    return LoginMethodConfigEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LoginMethodConfigEntry>): LoginMethodConfigEntry {
    const message = createBaseLoginMethodConfigEntry();
    message.main = object.main ?? false;
    message.android = object.android ?? undefined;
    message.ios = object.ios ?? undefined;
    return message;
  },
};

function createBaseLoginMethodConfigV2(): LoginMethodConfigV2 {
  return {
    phoneNumberLoginWithPassword: undefined,
    playerLoginOrRegisterWithSMS: undefined,
    playerLoginOrRegisterWithViber: undefined,
    playerLoginOrRegisterWithFacebook: undefined,
    biometric: undefined,
    emailLoginWithPassword: undefined,
    playerLoginOrRegisterWithEmailSMS: undefined,
    playerLoginOrRegisterWithTelegram: undefined,
    playerLoginOrRegisterWithWhatsapp: undefined,
    playerLoginOrRegisterWithApple: undefined,
    playerLoginOrRegisterWithPasskey: undefined,
  };
}

export const LoginMethodConfigV2: MessageFns<LoginMethodConfigV2> = {
  encode(message: LoginMethodConfigV2, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.phoneNumberLoginWithPassword !== undefined) {
      LoginMethodConfigEntry.encode(message.phoneNumberLoginWithPassword, writer.uint32(10).fork()).join();
    }
    if (message.playerLoginOrRegisterWithSMS !== undefined) {
      LoginMethodConfigEntry.encode(message.playerLoginOrRegisterWithSMS, writer.uint32(18).fork()).join();
    }
    if (message.playerLoginOrRegisterWithViber !== undefined) {
      LoginMethodConfigEntry.encode(message.playerLoginOrRegisterWithViber, writer.uint32(26).fork()).join();
    }
    if (message.playerLoginOrRegisterWithFacebook !== undefined) {
      LoginMethodConfigEntry.encode(message.playerLoginOrRegisterWithFacebook, writer.uint32(34).fork()).join();
    }
    if (message.biometric !== undefined) {
      LoginMethodConfigEntry.encode(message.biometric, writer.uint32(42).fork()).join();
    }
    if (message.emailLoginWithPassword !== undefined) {
      LoginMethodConfigEntry.encode(message.emailLoginWithPassword, writer.uint32(50).fork()).join();
    }
    if (message.playerLoginOrRegisterWithEmailSMS !== undefined) {
      LoginMethodConfigEntry.encode(message.playerLoginOrRegisterWithEmailSMS, writer.uint32(58).fork()).join();
    }
    if (message.playerLoginOrRegisterWithTelegram !== undefined) {
      LoginMethodConfigEntry.encode(message.playerLoginOrRegisterWithTelegram, writer.uint32(66).fork()).join();
    }
    if (message.playerLoginOrRegisterWithWhatsapp !== undefined) {
      LoginMethodConfigEntry.encode(message.playerLoginOrRegisterWithWhatsapp, writer.uint32(74).fork()).join();
    }
    if (message.playerLoginOrRegisterWithApple !== undefined) {
      LoginMethodConfigEntry.encode(message.playerLoginOrRegisterWithApple, writer.uint32(82).fork()).join();
    }
    if (message.playerLoginOrRegisterWithPasskey !== undefined) {
      LoginMethodConfigEntry.encode(message.playerLoginOrRegisterWithPasskey, writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginMethodConfigV2 {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLoginMethodConfigV2();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.phoneNumberLoginWithPassword = LoginMethodConfigEntry.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.playerLoginOrRegisterWithSMS = LoginMethodConfigEntry.decode(reader, reader.uint32());
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.playerLoginOrRegisterWithViber = LoginMethodConfigEntry.decode(reader, reader.uint32());
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.playerLoginOrRegisterWithFacebook = LoginMethodConfigEntry.decode(reader, reader.uint32());
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.biometric = LoginMethodConfigEntry.decode(reader, reader.uint32());
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.emailLoginWithPassword = LoginMethodConfigEntry.decode(reader, reader.uint32());
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.playerLoginOrRegisterWithEmailSMS = LoginMethodConfigEntry.decode(reader, reader.uint32());
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.playerLoginOrRegisterWithTelegram = LoginMethodConfigEntry.decode(reader, reader.uint32());
            continue;
          }
          case 9: {
            if (tag !== 74) {
              break;
            }

            message.playerLoginOrRegisterWithWhatsapp = LoginMethodConfigEntry.decode(reader, reader.uint32());
            continue;
          }
          case 10: {
            if (tag !== 82) {
              break;
            }

            message.playerLoginOrRegisterWithApple = LoginMethodConfigEntry.decode(reader, reader.uint32());
            continue;
          }
          case 11: {
            if (tag !== 90) {
              break;
            }

            message.playerLoginOrRegisterWithPasskey = LoginMethodConfigEntry.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): LoginMethodConfigV2 {
    return {
      phoneNumberLoginWithPassword: isSet(object.phoneNumberLoginWithPassword)
        ? LoginMethodConfigEntry.fromJSON(object.phoneNumberLoginWithPassword)
        : undefined,
      playerLoginOrRegisterWithSMS: isSet(object.playerLoginOrRegisterWithSMS)
        ? LoginMethodConfigEntry.fromJSON(object.playerLoginOrRegisterWithSMS)
        : undefined,
      playerLoginOrRegisterWithViber: isSet(object.playerLoginOrRegisterWithViber)
        ? LoginMethodConfigEntry.fromJSON(object.playerLoginOrRegisterWithViber)
        : undefined,
      playerLoginOrRegisterWithFacebook: isSet(object.playerLoginOrRegisterWithFacebook)
        ? LoginMethodConfigEntry.fromJSON(object.playerLoginOrRegisterWithFacebook)
        : undefined,
      biometric: isSet(object.biometric) ? LoginMethodConfigEntry.fromJSON(object.biometric) : undefined,
      emailLoginWithPassword: isSet(object.emailLoginWithPassword)
        ? LoginMethodConfigEntry.fromJSON(object.emailLoginWithPassword)
        : undefined,
      playerLoginOrRegisterWithEmailSMS: isSet(object.playerLoginOrRegisterWithEmailSMS)
        ? LoginMethodConfigEntry.fromJSON(object.playerLoginOrRegisterWithEmailSMS)
        : undefined,
      playerLoginOrRegisterWithTelegram: isSet(object.playerLoginOrRegisterWithTelegram)
        ? LoginMethodConfigEntry.fromJSON(object.playerLoginOrRegisterWithTelegram)
        : undefined,
      playerLoginOrRegisterWithWhatsapp: isSet(object.playerLoginOrRegisterWithWhatsapp)
        ? LoginMethodConfigEntry.fromJSON(object.playerLoginOrRegisterWithWhatsapp)
        : undefined,
      playerLoginOrRegisterWithApple: isSet(object.playerLoginOrRegisterWithApple)
        ? LoginMethodConfigEntry.fromJSON(object.playerLoginOrRegisterWithApple)
        : undefined,
      playerLoginOrRegisterWithPasskey: isSet(object.playerLoginOrRegisterWithPasskey)
        ? LoginMethodConfigEntry.fromJSON(object.playerLoginOrRegisterWithPasskey)
        : undefined,
    };
  },

  toJSON(message: LoginMethodConfigV2): unknown {
    const obj: any = {};
    if (message.phoneNumberLoginWithPassword !== undefined) {
      obj.phoneNumberLoginWithPassword = LoginMethodConfigEntry.toJSON(message.phoneNumberLoginWithPassword);
    }
    if (message.playerLoginOrRegisterWithSMS !== undefined) {
      obj.playerLoginOrRegisterWithSMS = LoginMethodConfigEntry.toJSON(message.playerLoginOrRegisterWithSMS);
    }
    if (message.playerLoginOrRegisterWithViber !== undefined) {
      obj.playerLoginOrRegisterWithViber = LoginMethodConfigEntry.toJSON(message.playerLoginOrRegisterWithViber);
    }
    if (message.playerLoginOrRegisterWithFacebook !== undefined) {
      obj.playerLoginOrRegisterWithFacebook = LoginMethodConfigEntry.toJSON(message.playerLoginOrRegisterWithFacebook);
    }
    if (message.biometric !== undefined) {
      obj.biometric = LoginMethodConfigEntry.toJSON(message.biometric);
    }
    if (message.emailLoginWithPassword !== undefined) {
      obj.emailLoginWithPassword = LoginMethodConfigEntry.toJSON(message.emailLoginWithPassword);
    }
    if (message.playerLoginOrRegisterWithEmailSMS !== undefined) {
      obj.playerLoginOrRegisterWithEmailSMS = LoginMethodConfigEntry.toJSON(message.playerLoginOrRegisterWithEmailSMS);
    }
    if (message.playerLoginOrRegisterWithTelegram !== undefined) {
      obj.playerLoginOrRegisterWithTelegram = LoginMethodConfigEntry.toJSON(message.playerLoginOrRegisterWithTelegram);
    }
    if (message.playerLoginOrRegisterWithWhatsapp !== undefined) {
      obj.playerLoginOrRegisterWithWhatsapp = LoginMethodConfigEntry.toJSON(message.playerLoginOrRegisterWithWhatsapp);
    }
    if (message.playerLoginOrRegisterWithApple !== undefined) {
      obj.playerLoginOrRegisterWithApple = LoginMethodConfigEntry.toJSON(message.playerLoginOrRegisterWithApple);
    }
    if (message.playerLoginOrRegisterWithPasskey !== undefined) {
      obj.playerLoginOrRegisterWithPasskey = LoginMethodConfigEntry.toJSON(message.playerLoginOrRegisterWithPasskey);
    }
    return obj;
  },

  create(base?: DeepPartial<LoginMethodConfigV2>): LoginMethodConfigV2 {
    return LoginMethodConfigV2.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LoginMethodConfigV2>): LoginMethodConfigV2 {
    const message = createBaseLoginMethodConfigV2();
    message.phoneNumberLoginWithPassword =
      (object.phoneNumberLoginWithPassword !== undefined && object.phoneNumberLoginWithPassword !== null)
        ? LoginMethodConfigEntry.fromPartial(object.phoneNumberLoginWithPassword)
        : undefined;
    message.playerLoginOrRegisterWithSMS =
      (object.playerLoginOrRegisterWithSMS !== undefined && object.playerLoginOrRegisterWithSMS !== null)
        ? LoginMethodConfigEntry.fromPartial(object.playerLoginOrRegisterWithSMS)
        : undefined;
    message.playerLoginOrRegisterWithViber =
      (object.playerLoginOrRegisterWithViber !== undefined && object.playerLoginOrRegisterWithViber !== null)
        ? LoginMethodConfigEntry.fromPartial(object.playerLoginOrRegisterWithViber)
        : undefined;
    message.playerLoginOrRegisterWithFacebook =
      (object.playerLoginOrRegisterWithFacebook !== undefined && object.playerLoginOrRegisterWithFacebook !== null)
        ? LoginMethodConfigEntry.fromPartial(object.playerLoginOrRegisterWithFacebook)
        : undefined;
    message.biometric = (object.biometric !== undefined && object.biometric !== null)
      ? LoginMethodConfigEntry.fromPartial(object.biometric)
      : undefined;
    message.emailLoginWithPassword =
      (object.emailLoginWithPassword !== undefined && object.emailLoginWithPassword !== null)
        ? LoginMethodConfigEntry.fromPartial(object.emailLoginWithPassword)
        : undefined;
    message.playerLoginOrRegisterWithEmailSMS =
      (object.playerLoginOrRegisterWithEmailSMS !== undefined && object.playerLoginOrRegisterWithEmailSMS !== null)
        ? LoginMethodConfigEntry.fromPartial(object.playerLoginOrRegisterWithEmailSMS)
        : undefined;
    message.playerLoginOrRegisterWithTelegram =
      (object.playerLoginOrRegisterWithTelegram !== undefined && object.playerLoginOrRegisterWithTelegram !== null)
        ? LoginMethodConfigEntry.fromPartial(object.playerLoginOrRegisterWithTelegram)
        : undefined;
    message.playerLoginOrRegisterWithWhatsapp =
      (object.playerLoginOrRegisterWithWhatsapp !== undefined && object.playerLoginOrRegisterWithWhatsapp !== null)
        ? LoginMethodConfigEntry.fromPartial(object.playerLoginOrRegisterWithWhatsapp)
        : undefined;
    message.playerLoginOrRegisterWithApple =
      (object.playerLoginOrRegisterWithApple !== undefined && object.playerLoginOrRegisterWithApple !== null)
        ? LoginMethodConfigEntry.fromPartial(object.playerLoginOrRegisterWithApple)
        : undefined;
    message.playerLoginOrRegisterWithPasskey =
      (object.playerLoginOrRegisterWithPasskey !== undefined && object.playerLoginOrRegisterWithPasskey !== null)
        ? LoginMethodConfigEntry.fromPartial(object.playerLoginOrRegisterWithPasskey)
        : undefined;
    return message;
  },
};

function createBaseOtpOrder(): OtpOrder {
  return {
    playerLoginOrRegisterWithSMS: undefined,
    playerLoginOrRegisterWithViber: undefined,
    playerLoginOrRegisterWithEmailSMS: undefined,
    playerLoginOrRegisterWithWhatsapp: undefined,
  };
}

export const OtpOrder: MessageFns<OtpOrder> = {
  encode(message: OtpOrder, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerLoginOrRegisterWithSMS !== undefined) {
      writer.uint32(8).int32(message.playerLoginOrRegisterWithSMS);
    }
    if (message.playerLoginOrRegisterWithViber !== undefined) {
      writer.uint32(16).int32(message.playerLoginOrRegisterWithViber);
    }
    if (message.playerLoginOrRegisterWithEmailSMS !== undefined) {
      writer.uint32(24).int32(message.playerLoginOrRegisterWithEmailSMS);
    }
    if (message.playerLoginOrRegisterWithWhatsapp !== undefined) {
      writer.uint32(32).int32(message.playerLoginOrRegisterWithWhatsapp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OtpOrder {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseOtpOrder();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.playerLoginOrRegisterWithSMS = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.playerLoginOrRegisterWithViber = reader.int32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.playerLoginOrRegisterWithEmailSMS = reader.int32();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.playerLoginOrRegisterWithWhatsapp = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): OtpOrder {
    return {
      playerLoginOrRegisterWithSMS: isSet(object.playerLoginOrRegisterWithSMS)
        ? globalThis.Number(object.playerLoginOrRegisterWithSMS)
        : undefined,
      playerLoginOrRegisterWithViber: isSet(object.playerLoginOrRegisterWithViber)
        ? globalThis.Number(object.playerLoginOrRegisterWithViber)
        : undefined,
      playerLoginOrRegisterWithEmailSMS: isSet(object.playerLoginOrRegisterWithEmailSMS)
        ? globalThis.Number(object.playerLoginOrRegisterWithEmailSMS)
        : undefined,
      playerLoginOrRegisterWithWhatsapp: isSet(object.playerLoginOrRegisterWithWhatsapp)
        ? globalThis.Number(object.playerLoginOrRegisterWithWhatsapp)
        : undefined,
    };
  },

  toJSON(message: OtpOrder): unknown {
    const obj: any = {};
    if (message.playerLoginOrRegisterWithSMS !== undefined) {
      obj.playerLoginOrRegisterWithSMS = Math.round(message.playerLoginOrRegisterWithSMS);
    }
    if (message.playerLoginOrRegisterWithViber !== undefined) {
      obj.playerLoginOrRegisterWithViber = Math.round(message.playerLoginOrRegisterWithViber);
    }
    if (message.playerLoginOrRegisterWithEmailSMS !== undefined) {
      obj.playerLoginOrRegisterWithEmailSMS = Math.round(message.playerLoginOrRegisterWithEmailSMS);
    }
    if (message.playerLoginOrRegisterWithWhatsapp !== undefined) {
      obj.playerLoginOrRegisterWithWhatsapp = Math.round(message.playerLoginOrRegisterWithWhatsapp);
    }
    return obj;
  },

  create(base?: DeepPartial<OtpOrder>): OtpOrder {
    return OtpOrder.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OtpOrder>): OtpOrder {
    const message = createBaseOtpOrder();
    message.playerLoginOrRegisterWithSMS = object.playerLoginOrRegisterWithSMS ?? undefined;
    message.playerLoginOrRegisterWithViber = object.playerLoginOrRegisterWithViber ?? undefined;
    message.playerLoginOrRegisterWithEmailSMS = object.playerLoginOrRegisterWithEmailSMS ?? undefined;
    message.playerLoginOrRegisterWithWhatsapp = object.playerLoginOrRegisterWithWhatsapp ?? undefined;
    return message;
  },
};

function createBaseThirdPartyOrder(): ThirdPartyOrder {
  return {
    playerLoginOrRegisterWithFacebook: undefined,
    playerLoginOrRegisterWithTelegram: undefined,
    playerLoginOrRegisterWithApple: undefined,
    biometric: undefined,
    playerLoginOrRegisterWithPasskey: undefined,
  };
}

export const ThirdPartyOrder: MessageFns<ThirdPartyOrder> = {
  encode(message: ThirdPartyOrder, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerLoginOrRegisterWithFacebook !== undefined) {
      writer.uint32(8).int32(message.playerLoginOrRegisterWithFacebook);
    }
    if (message.playerLoginOrRegisterWithTelegram !== undefined) {
      writer.uint32(16).int32(message.playerLoginOrRegisterWithTelegram);
    }
    if (message.playerLoginOrRegisterWithApple !== undefined) {
      writer.uint32(24).int32(message.playerLoginOrRegisterWithApple);
    }
    if (message.biometric !== undefined) {
      writer.uint32(32).int32(message.biometric);
    }
    if (message.playerLoginOrRegisterWithPasskey !== undefined) {
      writer.uint32(40).int32(message.playerLoginOrRegisterWithPasskey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ThirdPartyOrder {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseThirdPartyOrder();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.playerLoginOrRegisterWithFacebook = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.playerLoginOrRegisterWithTelegram = reader.int32();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.playerLoginOrRegisterWithApple = reader.int32();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.biometric = reader.int32();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.playerLoginOrRegisterWithPasskey = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ThirdPartyOrder {
    return {
      playerLoginOrRegisterWithFacebook: isSet(object.playerLoginOrRegisterWithFacebook)
        ? globalThis.Number(object.playerLoginOrRegisterWithFacebook)
        : undefined,
      playerLoginOrRegisterWithTelegram: isSet(object.playerLoginOrRegisterWithTelegram)
        ? globalThis.Number(object.playerLoginOrRegisterWithTelegram)
        : undefined,
      playerLoginOrRegisterWithApple: isSet(object.playerLoginOrRegisterWithApple)
        ? globalThis.Number(object.playerLoginOrRegisterWithApple)
        : undefined,
      biometric: isSet(object.biometric) ? globalThis.Number(object.biometric) : undefined,
      playerLoginOrRegisterWithPasskey: isSet(object.playerLoginOrRegisterWithPasskey)
        ? globalThis.Number(object.playerLoginOrRegisterWithPasskey)
        : undefined,
    };
  },

  toJSON(message: ThirdPartyOrder): unknown {
    const obj: any = {};
    if (message.playerLoginOrRegisterWithFacebook !== undefined) {
      obj.playerLoginOrRegisterWithFacebook = Math.round(message.playerLoginOrRegisterWithFacebook);
    }
    if (message.playerLoginOrRegisterWithTelegram !== undefined) {
      obj.playerLoginOrRegisterWithTelegram = Math.round(message.playerLoginOrRegisterWithTelegram);
    }
    if (message.playerLoginOrRegisterWithApple !== undefined) {
      obj.playerLoginOrRegisterWithApple = Math.round(message.playerLoginOrRegisterWithApple);
    }
    if (message.biometric !== undefined) {
      obj.biometric = Math.round(message.biometric);
    }
    if (message.playerLoginOrRegisterWithPasskey !== undefined) {
      obj.playerLoginOrRegisterWithPasskey = Math.round(message.playerLoginOrRegisterWithPasskey);
    }
    return obj;
  },

  create(base?: DeepPartial<ThirdPartyOrder>): ThirdPartyOrder {
    return ThirdPartyOrder.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ThirdPartyOrder>): ThirdPartyOrder {
    const message = createBaseThirdPartyOrder();
    message.playerLoginOrRegisterWithFacebook = object.playerLoginOrRegisterWithFacebook ?? undefined;
    message.playerLoginOrRegisterWithTelegram = object.playerLoginOrRegisterWithTelegram ?? undefined;
    message.playerLoginOrRegisterWithApple = object.playerLoginOrRegisterWithApple ?? undefined;
    message.biometric = object.biometric ?? undefined;
    message.playerLoginOrRegisterWithPasskey = object.playerLoginOrRegisterWithPasskey ?? undefined;
    return message;
  },
};

function createBaseLoginMethodOrder(): LoginMethodOrder {
  return { otp: undefined, thirdParty: undefined };
}

export const LoginMethodOrder: MessageFns<LoginMethodOrder> = {
  encode(message: LoginMethodOrder, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.otp !== undefined) {
      OtpOrder.encode(message.otp, writer.uint32(10).fork()).join();
    }
    if (message.thirdParty !== undefined) {
      ThirdPartyOrder.encode(message.thirdParty, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginMethodOrder {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLoginMethodOrder();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.otp = OtpOrder.decode(reader, reader.uint32());
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.thirdParty = ThirdPartyOrder.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): LoginMethodOrder {
    return {
      otp: isSet(object.otp) ? OtpOrder.fromJSON(object.otp) : undefined,
      thirdParty: isSet(object.thirdParty) ? ThirdPartyOrder.fromJSON(object.thirdParty) : undefined,
    };
  },

  toJSON(message: LoginMethodOrder): unknown {
    const obj: any = {};
    if (message.otp !== undefined) {
      obj.otp = OtpOrder.toJSON(message.otp);
    }
    if (message.thirdParty !== undefined) {
      obj.thirdParty = ThirdPartyOrder.toJSON(message.thirdParty);
    }
    return obj;
  },

  create(base?: DeepPartial<LoginMethodOrder>): LoginMethodOrder {
    return LoginMethodOrder.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LoginMethodOrder>): LoginMethodOrder {
    const message = createBaseLoginMethodOrder();
    message.otp = (object.otp !== undefined && object.otp !== null) ? OtpOrder.fromPartial(object.otp) : undefined;
    message.thirdParty = (object.thirdParty !== undefined && object.thirdParty !== null)
      ? ThirdPartyOrder.fromPartial(object.thirdParty)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
